/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "traitimg.h"


void
addprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	image  addproc_moy_1_arg;
	int  *result_2;
	image  addproc_med_1_arg;
	int  *result_3;
	image  addproc_hist_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADDPROG, ADDVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = addproc_moy_1(&addproc_moy_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = addproc_med_1(&addproc_med_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = addproc_hist_1(&addproc_hist_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	addprog_1 (host);
exit (0);
}
