/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "traitimg.h"

bool_t
xdr_image (XDR *xdrs, image *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->h))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->l))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->m))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->n))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->h);
		IXDR_PUT_LONG(buf, objp->l);
		IXDR_PUT_LONG(buf, objp->m);
		IXDR_PUT_LONG(buf, objp->n);
		}
		 if (!xdr_vector (xdrs, (char *)objp->tab_input, 2500,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->tab_output, 2500,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->h))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->l))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->m))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->n))
				 return FALSE;

		} else {
		objp->h = IXDR_GET_LONG(buf);
		objp->l = IXDR_GET_LONG(buf);
		objp->m = IXDR_GET_LONG(buf);
		objp->n = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->tab_input, 2500,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->tab_output, 2500,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->h))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->l))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->m))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tab_input, 2500,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tab_output, 2500,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
