/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRAITIMG_H_RPCGEN
#define _TRAITIMG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct image {
	int h;
	int l;
	int m;
	int n;
	char tab_input[2500];
	char tab_output[2500];
};
typedef struct image image;

#define ADDPROG 0x20000000
#define ADDVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADDPROC_MOY 1
extern  int * addproc_moy_1(image *, CLIENT *);
extern  int * addproc_moy_1_svc(image *, struct svc_req *);
#define ADDPROC_MED 2
extern  int * addproc_med_1(image *, CLIENT *);
extern  int * addproc_med_1_svc(image *, struct svc_req *);
#define ADDPROC_HIST 3
extern  int * addproc_hist_1(image *, CLIENT *);
extern  int * addproc_hist_1_svc(image *, struct svc_req *);
extern int addprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADDPROC_MOY 1
extern  int * addproc_moy_1();
extern  int * addproc_moy_1_svc();
#define ADDPROC_MED 2
extern  int * addproc_med_1();
extern  int * addproc_med_1_svc();
#define ADDPROC_HIST 3
extern  int * addproc_hist_1();
extern  int * addproc_hist_1_svc();
extern int addprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_image (XDR *, image*);

#else /* K&R C */
extern bool_t xdr_image ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRAITIMG_H_RPCGEN */
