/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "traitimg.h"

int *
addproc_moy_1_svc(image *argp, struct svc_req *rqstp)
{
	static image_t result;
	int somme;

	return &result;
}

int *
addproc_med_1_svc(image *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
addproc_hist_1_svc(image *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
